page_title: LF Builds

repos:
  - repo: ig-game-tokenrace
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-fn-sumosmash
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-omega-pinch
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-wordfind
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-team-word-race
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-bubblepopper
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-simple-speak
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-karts
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-scribble
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-eggball
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-higher-or-lower
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-obstacle-course
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-wave-survival
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-block-battle
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-codenames
    owner: Internet-Game
    smoke-test: release.yml

  - repo: ig-game-who-said-what
    owner: Internet-Game
    smoke-test: release.yml                           

  # - repo: asv-formatter
  #   owner: lincc-frameworks
  #   smoke-test: smoke-test.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: hipscat
  #   owner: astronomy-commons
  #   smoke-test: smoke-test.yml
  #   build-docs: build-documentation.yml
  #   benchmarks: asv-nightly.yml
  #   live-build: testing-and-coverage.yml

  # - repo: hipscat-cloudtests
  #   owner: astronomy-commons
  #   smoke-test: smoke-test.yml
  #   benchmarks: asv-nightly.yml
  #   live-build: testing-and-coverage.yml

  # - repo: hipscat-import
  #   owner: astronomy-commons
  #   smoke-test: smoke-test.yml
  #   build-docs: build-documentation.yml
  #   live-build: testing-and-coverage.yml

  # - repo: kbmod
  #   owner: dirac-institute
  #   smoke-test: canary_builds.yaml
  #   build-docs: build_docs.yaml
  #   live-build: pr_tests.yaml
  
  # - repo: koffi
  #   owner: lincc-frameworks
  #   smoke-test: smoke-test.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: lsdb
  #   owner: astronomy-commons
  #   smoke-test: smoke-test.yml
  #   build-docs: build-documentation.yml
  #   benchmarks: asv-nightly.yml
  #   live-build: testing-and-coverage.yml
      
  # - repo: python-project-template
  #   owner: lincc-frameworks
  #   live-build: ci.yml
  #   smoke-test: smoke-test.yml
  
  # - repo: rail
  #   owner: lsstdesc
  #   smoke-test: smoke-test.yml
  #   build-docs: build_documentation.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: rail_base
  #   owner: lsstdesc
  #   smoke-test: smoke-test.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: rail_pipelines
  #   owner: lsstdesc
  #   smoke-test: smoke-test.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: tables_io
  #   owner: lsstdesc
  #   smoke-test: smoke-test.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: tape
  #   owner: lincc-frameworks
  #   smoke-test: smoke-test.yml
  #   build-docs: build-documentation.yml
  #   live-build: testing-and-coverage.yml
  
  # - repo: tape_benchmarking
  #   owner: lincc-frameworks
  #   smoke-test: smoke-test.yml
  #   build-docs: build-documentation.yml
  #   live-build: testing-and-coverage.yml
