on:
  workflow_dispatch:
  push:
jobs:
  demo_get_tape_runs:
    runs-on: ubuntu-latest
#    permissions:
#      issues: read
    steps:
      - uses: actions/checkout@v3
      - run: |
          python update.py
#      - env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          curl --request GET \
#          --url "https://api.github.com/repos/lincc-frameworks/tape/issues" \
#          --header "Accept: application/vnd.github+json" \
#          --header "Authorization: Bearer $GH_TOKEN"
