on:
  workflow_dispatch:
jobs:
  demo_get:
    runs-on: ubuntu-latest
    steps:
      - name: get get get
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl --location 'https://api.github.com/repos/lincc-frameworks/tape/actions/runs' \
          --header 'accept: application/vnd.github+json' \
          --header 'Authorization: Bearer $PAT'
